name: Repository Dispatch
on:
  repository_dispatch:
    types: [tests]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Dump the client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"

      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
        if: github.event.client_payload.ref != ''
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Echo SHA
        env:
          CLIENT_SHA: ${{ github.event.client_payload.sha }}
        run: echo "$CLIENT_SHA"
